vishen/go-chromecast

README.md, cast_connection.go, cast_dns.go, main.go
You can list available Chromecasts and target specifically one of them with `-u` flag. It should work as before (i.e. using the first available Chromecast) when you don't specify the uuid.
=> Added support for multiple Chromecasts

cmd/ls.go
Add a 'ls' command that will list all available cast devices, this
should include chromecasts and google home devices.
Updates #5
=> cmd: added ls command

application/application.go, cmd/ls.go, cmd/status.go
Basic retry mechanism for when the device becomes unavailable for
whatever reason. We do this in the 'Update' function. This is called
quite often so seems like the best place to do this.
Closes #10
=> application: added a basic retry for if the device becomes unavailable

README.md, application/application.go
Chromecast supports FLAC natively, just a matter of detecting the file-extension and supplying the right media-type.
Awesome project by the way JP!
=> FLAC audio support

README.md, cmd/tts.go, tts/tts.go
Hi,
This tool is a very useful tool for me. Thank you.
I want to use the Text-to-Speech feature in Japanese, so I added the `--language-code` option in tts subcommand.
=> Make Text-to-Speech language selectable

README.md, cmd/volume.go
The volume subcommand can get and change volumes.
I want to change the volume instantly like below.
```bash
saved_volume=$(go-chromecast -n $NODE_NAME volume)
go-chromecast -n $NODE_NAME tts "$MESSAGE" --google-service-account ~/account.json
go-chromecast -n $NODE_NAME volume saved_volume
```
=> Add volume subcommand

application/application.go, go.mod
Cromecast generations 1 and 2 can only use mp3 or aac audio codecs.
ffmpeg already defaulted to aac it seems, but the chromecast would
immediately error if the original audio had more than two channels,
which is not supported. Force two channels.
While at it, remove the buggy use of ExitError. Its Stderr field is only
set by calling Cmd.Output, which we don't. Instead, make --debug send
ffmpeg's stderr directly to os.Stderr. This is very useful when
debugging ffmpeg issues.
=> application: specify the audio codec

.goreleaser.yml, cmd/root.go, go.mod, main.go
Added a version flag '--version' which will output the current release
and the git commit short sha. These are compiled into the binary when
from goreleaser.
Fixes: #28
=> version: added version flag

application/application.go, cmd/load.go, cmd/tts.go
Fix a bug where go-chromecast wouldn't exit if the media was externally
loaded media content.
Added a detach flag for 'load' which will exit as soon as external media
content has been loaded.
Fixes: #36
=> cmd,application: exit when external media finished playing

ui/update_status.go
When using the ui, the play/pause button does not "work" when the media state is changed from an other remote (it works the second time you press it though).
This will sync the ui `paused` boolean with the media status.
=> ui: sync paused state with media player state

README.md, application/application.go
Hi,
Google Cast supports WAV so there is no reason not to support it here, too.
=> Add WAV support

application/application.go, cast/connection.go
I was having trouble casting local files. It ended up being because go-chromecast was picking a 169.254.x.x IP address in `getLocalIP()` and telling the Chromecast to connect to that address for the embedded HTTP server. This pull request changes the logic to instead get the local IP address from the existing TCP connection to the Cast device, which I think will be more robust on multi-homed hosts.
Incidentally I've been using this on Windows (which works well so far). Thanks for making go-chromecast!
=> Use local IP from existing conn for local server

README.md, application/application.go, cmd/slideshow.go, testdata/helptext.txt
Added a slideshow command to display images on the chromecast. These can
be shows on repeat, or not repeated. There is a duration flag for how
long an image should be displayed on the chromecast. This has all been
coded into 'go-chromecast' because I can't get the duration to work with
the chromecast.
Updates: #49
=> cmd/slideshow: add a slideshow command

ui/ui.go, ui/update_status.go
Unless I'm missing something, it looks like the UI never updates the volume indicator with the value from received status messages (it only updates when changed locally in the UI). This, combined with the default value of 100% means that the volume up action says "Already at max" and volume down sets the volume at 0.95 which can be very loud depending on speaker settings.
This PR updates the volume UI based on the status messages in the same manner as the progress UI. Additionally, it changes the default volume value to 0 before a status message is received to prevent accidentally setting a very loud volume.
I'm using go-chromecast with Chromecast Audio devices which is why this is a problem. I suspect regular video Chromecast devices don't typically use the volume control, relying on the …
=> Set UI volume based on received status messages

cmd/ls.go, cmd/root.go, cmd/utils.go, dns/dns.go, go.mod, go.sum, testdata/helptext.txt
Changed the cast dns api to return a channel which is then used to
return the cast dns entry to use quicker if specifying a name, uuid or
device type since we no longer wait for all the dns entries to be
returned.
Use zeroconf rather than mdns since it provides a nicer api and allows
us to pass in a context for cancellation / timeout.
Added --first commands which will use the first cast dns entry found.
Closes: #58
=> dns: use channel based api to stream faster dns results

application/application.go, cmd/transcode.go, testdata/helptext.txt
Added a new command : transcode.
It needs 2 flags to be set in order to work:
-  content-type : string containing the content-type of what the transcoded output should have
-  command : string containing the command to execute. It should write its output to stdout
It's almost a rip off of the load command except its aim is to handle borderline case that the load command can't
=> Added transcoded command

application/application.go
The 'Plex' chromecast application doesn't seem to support relative time
seeking. Add a special case to do an absolute seek if it is a Plex app.
Updates: #38
=> application: add special case to handle Plex in 'Seek'

README.md, cmd/tts.go, tts/tts.go
Voice name is more powerful.
Google docs I have used: LINK
Available voices: https://cloud.google.com/text-to-speech/
Could you create a release after merging this PR?
I would do it myself, but I have troubles installing goreleaser.
Thanks in advance
Bartek
=> TTS: Added voice-name attribute for tts instead of languageCode (fixed)

README.md, application/application.go, cmd/load-app.go, testdata/helptext.txt
Add a new command to load a specific app on the chromecast and play the
content id. This should be useful for loading media on arbitrary
chromecast apps.
Updates: #90
=> cmd/load-app: Load chromecast App and Content ID

dns/dns.go
Just a quick fix to use the ipv6 address when the ipv4 is nil while connecting to a chromecast device
=> Quick fix for ipv6 only dns entry

application/application.go
This allows to embed go-chromecast into an application that already uses the DefaultServeMux.
=> Don't use the DefaultServeMux.

application/application.go, cmd/root.go, cmd/utils.go, testdata/helptext.txt
New option: -s, --server-port
If the option is omitted, the behavior is the same than before.
This is required if a firewall is blocking ports on the local machine
=> Allow to choose the Streaming Server port

http/handlers.go
Fix #104 .
It should be noticed that `/disconnect-all` already does the same.
=> Remove app even if an error occured on /disconnect

http/handlers.go
Add a new `ServeMux` and a `ServeHTTP` method, making it easier to embed the api in other servers.
Example:
```
// gin
router.Any("/cast/*any", gin.WrapH(http.StripPrefix("/cast", casthttp.NewHandler(false))))
```
=> feat: implement the net/http.Handler interface for Handler

cmd/playlist.go
Given a video file `a.mp4` in playlist `/video`, `Application.PlayableMediaType()` receives only `a.mp4`, which makes the `filetype.MatchFile()` in `Application.possibleContentType()` resolves it to `./a.mp4`, thus returns `os.ErrNotExist`
This commit fixes this bug.
=> fix cmd/playlist report zero playable files with foreign dir

.github/workflows/test.yml, dns/dns.go, dns/dns_test.go
Some DNS entries seem to include escaped utf8 bytes in the name, ie:
'"\200\300\200"'. Attempt to decode the utf8 bytes if it looks like they
are present in the name.
=> dns: attempt to decode escaped utf8 name

cmd/load.go
When the load subcommand executes, if the UI is loaded, the load is
launched in a go routine, then the UI is started on the main thread.  On
the other hand, if the UI is not started, the load subcommand executes
on the main thread.  However, on exit-ing the UI, the thread
inappropriately continues and re-executes the load, causing the casting
to restart from the beginning.  This simple fix causes the UI path to
return instead of falling through to the non-UI path.
Note, this behavior is benign when the video is playing, and exiting the
UI does not appear to cause any bad behavior.  However, if a video is
played to the end, such the 'load' execution is completed, then, when
exiting the UI, the second invocation of load will cause the video to
begin playing once more.
Signed-off-by: Jason …
=> Fix exit behavior for load with UI

application/application.go, application/errors.go, cast/connection.go, cmd/togglepause.go
I have added the `togglepause` command that will toggle the paused/unpaused state of the currently playing media. It works by checking the current state and then pausing/unpausing accordingly.  
This is convenient when using `go-chromecast` in other scripts. Previously, this wasn't possible without first checking the current state with a separate command.
I have also added `tpause` and `playpause` as aliases and fixed a few typos and misspellings that I noticed along the way.
Please look through my changes and let me know what you think!
=> Add a togglepause command

application/application.go, cast/connection.go
Hello!
go-chromecast is an amazing tool. I am writing a Go implementation of sponsorblockcast called [CastSponsorSkip](https://github.com/gabe565/CastSponsorSkip) and have noticed if a device disconnects and I call `Application.Close()`, some Goroutines never exit resulting in a slight memory leak.
The problematic functions are:
- [`Application.messageChanHandler()`](https://github.com/vishen/go-chromecast/blob/540b4afe3aa42821079c56e11f29d620185fb81d/application/application.go#L212) due to [`Application.messageChan`](https://github.com/vishen/go-chromecast/blob/540b4afe3aa42821079c56e11f29d620185fb81d/application/application.go#L100) not being closed.
- [`Application.recvMessages()`](https://github.com/vishen/go-chromecast/blob/540b4afe3aa42821079c56e11f29d620185fb81d/application/applicat …
=> fix: Fix Goroutine leak after calling Close

application/application.go
This PR adds configuration for `Application.Skipad()`, allowing for the sleep time or the number of retries to be changed.
=> feat: Add configuration for skip ad sleep time and retries

application/application.go, cast/connection.go
Ever since #166, `application.Close()` will panic with `close of closed channel` if closed more than once. This PR wraps the close call with `sync.Once.Do()` so that it can only be called once. This will cause the channel close to simply be skipped after the first call.
This could also be done with a non-blocking select, but has the downside of skipping the close if one of the channels happens to have data at the time that close is called. Let me know if you prefer this other method:
```go
defer func() {
select {
case <-a.messageChan:
// chan probably closed
default:
// chan not closed
close(a.messageChan)
}
}()
```
=> fix: Ensure channels are only closed once

application/application.go, application/application_test.go, go.mod, go.sum, playlists/playlist_test.go, playlists/playlists.go, playlists/testdata/indiepop130.m3u, playlists/testdata/indiepop64.pls, playlists/utlis.go, testdata/indiepop64.pls
This makes it so one can do 
```
$ go-chromecast -a 192.168.50.88 load https://somafm.com/indiepop64.pls
```
Maybe this is already supported? I didn't see it, if so.
=> implement support for .pls and .m3u -playlists

cmd/scan.go, go.mod, go.sum
This PR adds a utility to do a little scan for chromecast devices. I'm using qubes os which has certan network restrictions, and having a hard time getting mDNS/avahi to function properly and find chromecast devices. 
Examples
```
$ go run . --cidr 192.168.50.0/24  scan
Scanning...  scanned 0, current 192.168.50.0:8009
Found (potential) chromecast at 192.168.50.88:8009
Scanned 256 uris in 1.605169203s
$ go run . --cidr 192.168.51.0/24  scan
Scanning...  scanned 0, current 192.168.51.0:8009
Scanned 256 uris in 1.606679062s
```
=> cmd: implement chromecast scanner

application/application.go, application/application_test.go, cmd/scan.go
This PR uses the http interface at `8008:setup/eureka_info` to pick out the device name, if a device has been found via scanning. 
```
$ go run .  scan --cidr 192.168.50.0/24 
Scanning...  scanned 0, current 192.168.50.0
- 'Office speaker' at 192.168.50.88:8009
Scanned 256 uris in 1.609840334s
```
Also removes some leftovers from a previous PR.
=> scanner: provide device name

application/application.go
The `fmt.Printf` messages are interfering with the `--with-ui` option - this changes them to use the log methods instead which appear properly inside the UI Log area.
=> Change fmt.Printf to log.Infof when adding items to playlist

README.md, cmd/tts.go, tts/tts.go
Hi,
go-chromecast is a very handy tool that I use every day on my home network.
I've tried making it even more convenient by supporting [SSML](https://cloud.google.com/text-to-speech/docs/ssml).
Added `--ssml` flag to treat messages as SSML
example:
```
go-chromecast tts '<speak>Hello<break time="500ms"/>world.</speak>' \
--google-service-account /path/to/google-cred.json --ssml
```
Please consider merging if you like.
=> Support SSML in Speech-to-text

http/types.go
Some devices (like Home-Mini) does not set 'app' when app is not running.
This led to /status http call to throw exeception. Added protection.
=> HTTP status should not throw when app is nil.

http/handlers.go
- **Implement 'POST /connect-all?wait=...&iface=...'**
- **Added autoconnect option.**
=> Implement 'POST /connect-all?wait=...&iface=...'

http/handlers.go
- **HTTP status should not throw when app is nil.**
- **Implement 'POST /connect-all?wait=...&iface=...'**
- **Added autoconnect option.**
- **Added support for: GET /statuses**
=> Support for: GET /statuses

application/application.go, cast/payload.go, http/handlers.go
The server's method /status was not updating the status in the app layer. 
As collecting all statuses for multiple devices is a slow operation, 
I'm proposing to add a background process to refresh them independently of requests.
=> HTTP Server: Statuses can be collected in the background

application/application.go
Package github.com/h2non/filetype returns "audio/mpeg" for MP3 files. go-chromecast currently only expects "audio/mp3" which appears to be deprecated. This change adds "audio/mpeg" to the list of recognized types which seems to be the correct type per RFC 3003.
=> Recognize "audio/mpeg" as MP3 to skip transcoding

README.md, cmd/volume-down.go, cmd/volume-up.go
This PR adds volume up / down command.
How to use:
```bash
$ go-chromecast volume-up
0.25
$ go-chromecast volume-up --step 0.10
0.35
$ go-chromecast volume-down
0.30
$ go-chromecast volume-down --step 0.10
0.20
```
=> feat: Add volume up / down command.

http/types.go
Fixes #220 
Reduce the amount of boilerplate code and make it easier to work with responses by breaking the various objects out.
Example original format
```json
{
"0dc845e291374610b86d0d3ff62eedf8": {
"info": {
"name": "Receiver",
"ip_address": "192.168.1.232",
"locale": "en-US",
"mac_address": "00:09:B0:3A:78:73",
"ssid": "",
"timezone": "America/Los_Angeles",
"uptime": 2653424.930453,
"ssdp_udn": "0dc845e2-9137-4610-b86d-0d3ff62eedf8"
},
"app_id": "2DB7CC49",
"display_name": "YouTube Music",
"is_idle_screen": false,
"status_text": "YouTube Music",
"player_state": "PLAYING",
"current_time": 24.241,
"idle_reason": "",
"current_item_id": 0,
"loading_item_id": 0,
"content_id": "p4lN2Jvl9RM",
"content_type": "x-youtube/video",
"stream_type": "BUFFERED",
"duration": 212.861,
"artist": "No …
```
=> Use existing device status objects

README.md, http/handlers.go
Fixes #222
Rename statuses to status-all and use statuses as a wrapper with deprecation notices
=> Deprecate statuses for status-all
